apiVersion: v1
name: remindr
version: 1.0.0
appVersion: 1.0.0
description: Event-driven I/O server-side JavaScript environment based on V8
keywords:
- node
- javascript
- nodejs
- git
- mongodb
home: http://nodejs.org/
sources:
- https://github.com/bitnami/bitnami-docker-node
maintainers:
- name: Juan Carlos Andreu
  email: contact@andreujuan.com
engine: gotpl
icon: https://bitnami.com/assets/stacks/nodejs/img/nodejs-stack-110x117.png
